FROM webhippie/alpine:latest AS build
RUN apk add --no-cache ca-certificates

FROM scratch

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="GitHub Exporter" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 9106
ENTRYPOINT ["/bin/github_exporter"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY dist/github_exporter-*-linux-arm /bin/github_exporter
